constraint_setting(
    name = "bootstrap",
    visibility = ["PUBLIC"],
)

constraint_value(
    name = "bootstrap_stage0",
    constraint_setting = ":bootstrap",
    visibility = ["PUBLIC"],
)

constraint_value(
    name = "bootstrap_stage1",
    constraint_setting = ":bootstrap",
    visibility = ["PUBLIC"],
)

constraint_value(
    name = "bootstrap_stage2",
    constraint_setting = ":bootstrap",
    visibility = ["PUBLIC"],
)

rust_binary(
    name = "hello",
    srcs = ["hello.rs"],
    crate_root = "hello.rs",
    visibility = ["PUBLIC"],
)
