constraint_setting(
    name = "rust_bootstrap_stage",
    visibility = ["PUBLIC"],
)

constraint_value(
    name = "stage0",
    constraint_setting = ":rust_bootstrap_stage",
    visibility = ["PUBLIC"],
)

constraint_value(
    name = "stage1",
    constraint_setting = ":rust_bootstrap_stage",
    visibility = ["PUBLIC"],
)

constraint_value(
    name = "stage2",
    constraint_setting = ":rust_bootstrap_stage",
    visibility = ["PUBLIC"],
)
