load("@bootstrap//tools:defs.bzl", "bootstrap_internal_tools")

bootstrap_internal_tools(
    name = "internal_tools",
    visibility = ["PUBLIC"],
)

python_bootstrap_binary(
    name = "assemble_sysroot",
    main = "assemble_sysroot.py",
    visibility = ["PUBLIC"],
)
