load("@prelude//toolchains:cxx.bzl", "system_cxx_toolchain")
load("@prelude//toolchains:python.bzl", "system_python_bootstrap_toolchain")
load("@bootstrap//:toolchain.bzl", "rust_bootstrap_toolchain")

system_cxx_toolchain(
    name = "cxx",
    visibility = ["PUBLIC"],
)

system_python_bootstrap_toolchain(
    name = "python_bootstrap",
    visibility = ["PUBLIC"],
)

rust_bootstrap_toolchain(
    name = "rust_bootstrap",
    visibility = ["PUBLIC"],
)

toolchain_alias(
    name = "rust",
    actual = select({
        "DEFAULT": ":rust_beta",
        "bootstrap//constraints:use_beta": ":rust_beta",
        # "bootstrap//constraints:use_stage0": ":rust_stage0",
        # "bootstrap//constraints:use_stage1": ":rust_stage1",
        # "bootstrap//constraints:use_stage1p": ":rust_stage1p",
        # "bootstrap//constraints:use_stage2": ":rust_stage2",
    }),
    visibility = ["PUBLIC"],
)

alias(
    name = "rust_beta",
    actual = "toolchains//rust-beta:rust",
)
